### ISSUE TITLE
Questions about background and transition encoding errors.

### ISSUE THREAD

**Issue by bortkiewicz** [OscarCunningham/logic-life-search#2]
For both "--bg" and "--bgos" the help just says "Specify a background", and I can't find any description or comment in source code. What does it mean? I'm interested.

Also, doing -M0 (Knuth CNF formatting, I saw in the forums) vs -M1 (Life CNF formatting) gives different results (was fooling around):

    dandan@Lenovo-H3060:~/Documents/logic-life-search$ ./lls --bg backgrounds/zebra -s p3 -a p1 -b 10 -M1

    Getting search pattern...
    Done

    Preprocessing...
    Done

    Number of undetermined cells: 300
    Number of variables: 902
    Number of clauses: 41573

    Active width: 10
    Active height: 10
    Active duration: 4

    Solving...
    Done

    Time taken: 0.664324045181 seconds

    x = 12, y = 12, rule = B3/S23
    bbbbbbbbbbbb$
    oooobboooooo$
    bbboooobobbb$
    obbbbbbboooo$
    bobbboobobob$
    obbbbbobobbo$
    bbbbbbobooob$
    obbbboobobbo$
    bobbbobbooob$
    obbbbboobbbo$
    bbbobbbbbobb$
    oooooooooooo!

    dandan@Lenovo-H3060:~/Documents/logic-life-search$ ./lls --bg backgrounds/zebra -s p3 -a p1 -b 10 -M0

    Getting search pattern...
    Done

    Preprocessing...
    Done

    Number of undetermined cells: 300
    Number of variables: 6626
    Number of clauses: 26577

    Active width: 10
    Active height: 10
    Active duration: 4

    Solving...
    Done

    Time taken: 0.010046005249 seconds

    Unsatisfiable

    dandan@Lenovo-H3060:~/Documents/logic-life-search$ 

(By the way I'm testitemqlstudop on conwaylife forums)

**Comment by OscarCunningham** [comment]
Yes, the help messages are very light at the moment, I aim to improve them before I merge the develop branch into master. I sent you a pm on conwaylife.com with some more details.

The -M0 problem was an oversight on my end that made -M0 incompatible with backgrounds. It's been fixed now.
